package bookStore.model.module.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.DBSequence;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 04 16:42:04 IST 2018
// ---------------------------------------------------------------------
public interface UserRegistrationAM extends ApplicationModule {
    DBSequence getNextDBSequence();
}
