package bookStore.model.module;

import bookStore.model.module.common.LibrarianChoresAM;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 09 12:22:48 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LibrarianChoresAMImpl extends ApplicationModuleImpl implements LibrarianChoresAM {
    /**
     * This is the default constructor (do not remove).
     */
    public LibrarianChoresAMImpl() {
    }

    public void applyQueryRecordByStatusVOCriteria(String b_Status) {
        //debug log
        System.out.println("------------------LibrarianChoresAMImpl.applyQueryRecordByStatusVOCriteria[b_Status : " + b_Status +
                           "]------------------");

        ViewObjectImpl vo = this.getQueryRecord1();
        ViewCriteria vc = vo.getViewCriteria("QueryRecordByStatusVOCriteria");
        vc.resetCriteria();
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("b_Status", b_Status.equals("ALL") ? null : b_Status);
        vo.applyViewCriteria(vc, true);
        vo.executeQuery();
    }

    /*  public void applySubmitBookByStatusVOCriteria(String b_recordType) {
        //debug log
        System.out.println("------------------LibrarianChoresAMImpl.applySubmitBookByStatusVOCriteria[b_recordType : " + b_recordType +
                           "]------------------");

        ViewObjectImpl vo = this.getSubmitBook1();
        ViewCriteria vc = vo.getViewCriteria("SubmitBookByStatusVOCriteria");
        vc.resetCriteria();
        VariableValueManager vvm = vc.ensureVariableManager();
        vvm.setVariableValue("b_recordType", b_recordType.equals("ALL") ? null : b_recordType);
        vo.applyViewCriteria(vc, true);
        vo.executeQuery();
    } */

    //Actually it is SubmitBookByReturnDateVOCriteria, named so to avoid change in jspx

    public void applySubmitBookByStatusVOCriteria(String b_recordType) {
        //debug log
        System.out.println("------------------LibrarianChoresAMImpl.applySubmitBookByStatusVOCriteria[b_recordType : " + b_recordType +
                           "]------------------");

        ViewObjectImpl vo = this.getSubmitBook1();

        if (b_recordType.contains("BOOKED")) {
            ViewCriteria vc = vo.getViewCriteria("SubmitBookByReturnDateVOCriteria");
            vc.resetCriteria();
            vo.applyViewCriteria(vc, true);
        }

        if (b_recordType.contains("ALL")) {
            vo.removeApplyViewCriteriaName("SubmitBookByReturnDateVOCriteria");
        }
        vo.executeQuery();
    }

    /**
     * Container's getter for UsersVOInstance.
     * @return UsersVOInstance
     */
    public ViewObjectImpl getUsersVOInstance() {
        return (ViewObjectImpl)findViewObject("UsersVOInstance");
    }

    /**
     * Container's getter for QueryRecord2.
     * @return QueryRecord2
     */
    public ViewObjectImpl getQueryRecord1() {
        return (ViewObjectImpl)findViewObject("QueryRecord1");
    }

    /**
     * Container's getter for QueryStatusCodeLOV1.
     * @return QueryStatusCodeLOV1
     */
    public ViewObjectImpl getQueryStatusCodeLOV1() {
        return (ViewObjectImpl)findViewObject("QueryStatusCodeLOV1");
    }

    /**
     * Container's getter for SubmitBook1.
     * @return SubmitBook1
     */
    public ViewObjectImpl getSubmitBook1() {
        return (ViewObjectImpl)findViewObject("SubmitBook1");
    }

    /**
     * Container's getter for QueryRecordStatusPieView1.
     * @return QueryRecordStatusPieView1
     */
    public ViewObjectImpl getQueryRecordStatusPieView1() {
        return (ViewObjectImpl)findViewObject("QueryRecordStatusPieView1");
    }

    /**
     * Container's getter for IssueRecordReserveFrequencyView1.
     * @return IssueRecordReserveFrequencyView1
     */
    public ViewObjectImpl getIssueRecordReserveFrequencyView1() {
        return (ViewObjectImpl)findViewObject("IssueRecordReserveFrequencyView1");
    }
}
