package bookStore.model.module.client;

import bookStore.model.module.common.LibrarianChoresAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 09 13:42:50 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LibrarianChoresAMClient extends ApplicationModuleImpl implements LibrarianChoresAM {
    /**
     * This is the default constructor (do not remove).
     */
    public LibrarianChoresAMClient() {
    }

    public void applyQueryRecordByStatusVOCriteria(String b_Status) {
        Object _ret = this.riInvokeExportedMethod(this,"applyQueryRecordByStatusVOCriteria",new String [] {"java.lang.String"},new Object[] {b_Status});
        return;
    }

    public void applySubmitBookByStatusVOCriteria(String b_recordType) {
        Object _ret = this.riInvokeExportedMethod(this,"applySubmitBookByStatusVOCriteria",new String [] {"java.lang.String"},new Object[] {b_recordType});
        return;
    }
}
