package bookStore.model.module.client;

import bookStore.model.module.common.UserRegistrationAM;

import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.DBSequence;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 04 16:42:04 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserRegistrationAMClient extends ApplicationModuleImpl implements UserRegistrationAM {
    /**
     * This is the default constructor (do not remove).
     */
    public UserRegistrationAMClient() {
    }


    public DBSequence getNextDBSequence() {
        Object _ret = this.riInvokeExportedMethod(this,"getNextDBSequence",null,null);
        return (DBSequence)_ret;
    }
}
